# Generated by Django 5.1.4 on 2025-01-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='featured_image',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='published_date',
        ),
    ]
