# Generated by Django 5.1.4 on 2025-01-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_rename_featured_image_blog_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/blog_images/'),
        ),
    ]
